# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 01:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='upload/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('creation_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrecipitationMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_rate', models.FloatField()),
                ('measure_datetime', models.DateTimeField()),
                ('observatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rain.Observatory')),
            ],
        ),
    ]
