# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rain', '0002_auto_20170402_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precipitationmeasurement',
            name='measure_datetime',
            field=models.DateTimeField(),
        ),
    ]
