# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatory',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='observatorylocation',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
