# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rain', '0003_auto_20170402_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precipitationmeasurement',
            name='precipitation_24hr',
        ),
    ]
